### ISSUE TITLE
Increased overall bundle.js by 4.4MB

### ISSUE THREAD

**Issue by colemerrick** [SeanMcP/a11y-react-emoji#10]
Ouch.  Why is that?  It seems like this lib should just be generating the correct html, like `<span aria-label="positive" role="img">😁</span>`?

**Comment by SeanMcP** [comment]
@colemerrick That's not ideal!

I'll look into this. Can you provide some before and after information to reference?

**Comment by colemerrick** [comment]
@SeanMcP Sorry, I didn't look into it much further.  Just that the production build increased from 3.6MB to 8MB.  I'm assuming you're loading an emoji library within or something?  It certainly would be nice to have a one stop shop for emoji's, but considering the file size increase I would put that responsibility to your users.  You could reference https://getemoji.com in the docs or something to help out.  My feedback anyways...

Thanks for building the lib, and posting on Medium btw!  I learned something.

**Comment by SeanMcP** [comment]
@colemerrick That's curious. [This library has no production dependencies](https://github.com/SeanMcP/a11y-react-emoji/blob/master/package.json), which means it should only add a trivial amount (the size of a few text files) to the build.

**Comment by SeanMcP** [comment]
I'm going to close this for now. Let me know if you have an example that I can see to troubleshoot.
