### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/a11y-react-emoji#15]
Follow the pattern here: https://keepachangelog.com/en/1.0.0/

**Comment by arturparkhisenko** [comment]
@SeanMcP Hi, it seems like we both like that pattern. I would be glad to do something useful and help there with this issue and maybe others :)

**Comment by SeanMcP** [comment]
@arturparkhisenko Sounds good! Fork this repository, make the changes, and then open a pull request that references this issue.

The process is the same for the other open issues too: one PR for every issue 👍
