### ISSUE TITLE
[Discussion] Accept children prop for emoji

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/a11y-react-emoji#19]
The current API for `Emoji` requires you pass the emoji string to a `symbol` prop. This is fine and doesn't need changing.

But what about also accepting the emoji passed as children? The new API would work like this:

```js
<Emoji label="a buzzing bee">🐝</Emoji>
```

I think children is what the user would expect. The tradeoff is that we would need to handle the scenario where both `symbol` and `children` are passed. Who would win in that instance? Or should an error be thrown?

**Comment by arturparkhisenko** [comment]
I would say that it's good to have it to follow the HTML semantics and those use cases like in that article [Accessible emoji](https://tink.uk/accessible-emoji/) from the readme. And in that case, I would like to give it priority over the `symbol` property.
