### ISSUE TITLE
Make `EmojiProps` interface an extension of `HTMLSpanElement`

### ISSUE THREAD

**Issue by bdbaraban** [SeanMcP/a11y-react-emoji#3]
I believe the `EmojiProps` interface should extend the `HTMLSpanElement` type. That way, additional `<span>` attributes can be directly passed as props to the `Emoji` component without raising type errors in TypeScript.

Recommendation:
```
interface EmojiProps extends React.HTMLAttributes<HTMLSpanElement> {
  label?: string;
  symbol: string;
}
```

Safely permits usage such as:
```
<Emoji label="dog" symbol="🐕" className="className" />
```

**Comment by SeanMcP** [comment]
That's a great suggestion, @bdbaraban! Are you interested in making the pull request?
